- name: Get namespace name
  hosts: bmcs-dex-us-ashburn-1
  collections:
    - oracle.oci
  tasks:
    - name: Get namespace name
      oci_object_storage_namespace_facts:
      register: output
    - name: Print namespace name
      debug:
        msg: "{{ output }}"
